import ClientProvider from '@/components/ClientProvider'
import Header from '@/components/Header'
import PromptInput from '@/components/PromptInput'
import '../styles/global.css'

export const metadata = {
  title: 'Ai-Image-Generator',
  description: 'Generated by Oren Sharizad',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <ClientProvider>
          <Header />
          <PromptInput />
          {children}
        </ClientProvider>
      </body>
    </html>
  )
}
